### ISSUE TITLE
Support JSX templates

### ISSUE THREAD

**Issue by brianmhunt** [knockout/tko.components#5]
Re: https://github.com/knockout/knockout/issues/1663

### Proposal:

Add `jsx` as an option to the `template` registration e.g.

```javascript
ko.components.register('test-widget', {
   viewModel: SomeTestWidgetViewModelClass,
   template: {
     jsx: /* JSX Things ...*/
   }
})
```

**Comment by brianmhunt** [comment]
... in reality, for future-proofing there should probably be a plugin system with `ko.components`.

**Comment by daedalus28** [comment]
Just a note about this - part of the advantage of JSX is the ability to use native js things instead of having custom DSLs (for example, using a simple `array.map` instead of learning bindings like `foreach`). For this to really shine, bindings themselves should also be able to be called as functions and ideally be able to be less KO specific. The ideal situation here is probably to internally allow using a template that is a function which becomes a computed so you can do all the things you'd do in react like `map`, etc and not have to have it map to some custom binding. React + MobX is a great example of this

**Comment by Tschaul** [comment]
Thats how i see it too. The knockout bindings would be gone / not needed anymore.

But knockout would have to do slightly more than handle the jsx template as computed observable. It has to instantiate other ko-Components that are used inside the template and handle their lifecylce. But that shouldn't be too different than what knockout is doing with the current templating logic.

**Comment by Tschaul** [comment]
I have a working proof of concept using the virtual-dom library here: https://github.com/Tschaul/hyperknock/blob/master/index.jsx

**Comment by brianmhunt** [comment]
When looking at a `foreach` binding you might want to have a look inside [`tko.binding.foreach`](https://github.com/knockout/tko.binding.foreach) - it keeps track of individual items in the DOM.
